/**
 * @file line_separator.h
 * @brief 换行符
 */

#pragma once
#ifndef EMDEVIF_CORE_LINE_SEPARATOR_H
#define EMDEVIF_CORE_LINE_SEPARATOR_H

#define EMDEVIF_LINE_SEPARATOR_CRLF      "\r\n"
#define EMDEVIF_LINE_SEPARATOR_LF        "\n"
#define EMDEVIF_LINE_SEPARATOR_CR        "\r"

#define EMDEVIF_LINE_SEPARATOR_MODE_CRLF 0
#define EMDEVIF_LINE_SEPARATOR_MODE_LF   1
#define EMDEVIF_LINE_SEPARATOR_MODE_CR   2

/**
 * @def EMDEVIF_LINE_SEPARATOR_MODE
 *
 * 换行符模式。指定为 @c EMDEVIF_LINE_SEPARATOR_MODE_CRLF （默认值）表示使用 CRLF；@n
 * 指定为 @c EMDEVIF_LINE_SEPARATOR_MODE_LF 使用 LF； @n
 * 指定为 @c EMDEVIF_LINE_SEPARATOR_MODE_CR 使用 CR
 */
#ifndef EMDEVIF_LINE_SEPARATOR_MODE
#define EMDEVIF_LINE_SEPARATOR_MODE EMDEVIF_LINE_SEPARATOR_MODE_CRLF
#endif

/**
 * @def EMDEVIF_LINE_SEPARATOR
 *
 * 换行符。通过指定宏 @ref EMDEVIF_LINE_SEPARATOR_MODE 决定使用哪一种换行符
 */
#if (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_CRLF)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_CRLF
#elif (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_LF)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_LF
#elif (EMDEVIF_LINE_SEPARATOR_MODE == EMDEVIF_LINE_SEPARATOR_MODE_CR)
#define EMDEVIF_LINE_SEPARATOR EMDEVIF_LINE_SEPARATOR_CR
#else
#error \
    "EMDEVIF_LINE_SEPARATOR_MODE can only be defined to `EMDEVIF_LINE_SEPARATOR_MODE_CRLF`, `EMDEVIF_LINE_SEPARATOR_MODE_LF` or `EMDEVIF_LINE_SEPARATOR_MODE_CR`"
#endif

#endif  // !EMDEVIF_CORE_LINE_SEPARATOR_H
